In [ ]:
#Importing Pandas
import pandas as pd

In [ ]:

#Loading of the dataset
covid = pd.read_csv('Covid.csv')
coviddf = pd.DataFrame(covid)

In [ ]:
#Previewing data
coviddf.head()

  iso_code continent  ... excess_mortality excess_mortality_cumulative_per_million
0      AFG      Asia  ...              NaN                                     NaN
1      AFG      Asia  ...              NaN                                     NaN
2      AFG      Asia  ...              NaN                                     NaN
3      AFG      Asia  ...              NaN                                     NaN
4      AFG      Asia  ...              NaN                                     NaN

[5 rows x 67 columns]

In [ ]:
#Renaming columns
renamed = {'hosp_patients':'hospitalized_patients','hosp_patients_per_million':'hospitalized_patients_per_million', 'weekly_hosp_admissions':'weekly_hospital_admissions','weekly_hosp_admissions_per_million' : 'weekly_hospital_admissions_per_million'}
coviddf.rename(columns = renamed, inplace =True)
coviddf.head()

  iso_code continent  ... excess_mortality excess_mortality_cumulative_per_million
0      AFG      Asia  ...              NaN                                     NaN
1      AFG      Asia  ...              NaN                                     NaN
2      AFG      Asia  ...              NaN                                     NaN
3      AFG      Asia  ...              NaN                                     NaN
4      AFG      Asia  ...              NaN                                     NaN

[5 rows x 67 columns]